- id: r1
  title: "Register for Corporation Tax"
  description: "You need to register within 3 months of starting to do business, if you have not done so already."
  url: "/corporation-tax"
  topic: Tax
  group: "Things you need to do next"
- id: r2
  title: "Check if you need any licences for your business"
  description: "You might need licences or to register your company, depending on the type of work you do."
  url: "/find-licences"
  topic: "Licences and registration"
  group: "Things you need to do next"
- id: r3
  title: "Check if you need insurance"
  description: "There are different types of insurance you might need, depending on your area of business."
  url: "https://www.abi.org.uk/products-and-issues/choosing-the-right-insurance/business-insurance/"
  topic: Insurance
  group: "Things you need to do next"
- id: r4
  title: "Check if you need to send a Self Assessment"
  description: "You might need to send a tax return if you have any untaxed income, such as dividends."
  url: "/check-if-you-need-tax-return"
  topic: Tax
  group: "Things you need to do next"
- id: r5
  title: "Selling goods or services"
  description: "Rules on how you offer your products or services."
  url: "/browse/business/sale-goods-services-data"
  topic: "Sale of goods or services"
  group: "Rules to follow"
- id: r6
  title: "Avoid anti-competitive activity"
  description: "You need to understand rules around price-fixing and competition."
  url: "/cartels-price-fixing"
  topic: "Competition law"
  group: "Rules to follow"
- id: r7
  title: "Learn how to deal with personal information"
  description: "If your business stores anyone's personal information, you need to know how to look after it."
  url: "/data-protection-your-business"
  topic: "Data protection"
  group: "Rules to follow"
- id: r8
  title: "Health and safety at work"
  description: "How to keep your employees and customers safe."
  url: "https://www.hse.gov.uk/guidance/index.htm"
  topic: "Health and safety"
  group: "Rules to follow"
- id: r9
  title: "How to run a limited company"
  description: "Your responsibilities when running a limited company."
  url: "/running-a-limited-company"
  topic: "Running a business"
  group: "Rules to follow"
- id: r10
  title: "Starting a business overview"
  description: "General guidance about starting and growing your business."
  url: "/browse/business/setting-up"
  topic: "Running a business"
  group: "Rules to follow"
- id: r11
  title: "Include your company details on stationery"
  description: "Make sure you include your company details on any stationery and promotional materials."
  url: "/running-a-limited-company/signs-stationery-and-promotional-material"
  topic: "Running a business"
  group: "Rules to follow"
- id: r12
  title: "How to dispose of your company's waste"
  description: "Reducing the waste you create, and what to do with it."
  url: "/managing-your-waste-an-overview"
  topic: Environment
  group: "Rules to follow"
- id: r13
  title: "Protect your brand or designs"
  description: "How to stop others copying your products, designs or brand."
  url: "/intellectual-property-an-overview"
  topic: "Intellectual property"
  group: "Good to know"
- id: r14
  title: "Get help from the Business Support Helpline"
  description: "Speak to the helpline to get advice for your business."
  url: "/business-support-helpline"
  topic: "Help and support"
  group: "Good to know"
- id: r15
  title: "Sign up for Companies House email reminders"
  description: "Get an email when your accounts and confirmation statement are due."
  url: "/guidance/register-for-email-reminders-from-companies-house"
  topic: "Help and support"
  group: "Good to know"
- id: r16
  title: "Register for VAT"
  description: "You need to register your business for VAT if your business takes more than £90,000 (the 'turnover'), if you have not already."
  url: "/vat-registration"
  topic: Tax
  group: "Things you need to do next"
- id: r17
  title: "Check if you'll need to register for VAT"
  description: "If your business takes more than £90,000 (the 'turnover'), you'll need to register for VAT."
  url: "/vat-registration/when-to-register"
  topic: Tax
  group: "Things you need to do next"
- id: r18
  title: "Check what to do before employing someone"
  description: "What you need to know about to employing people."
  url: "/get-ready-to-employ-someone"
  topic: "Employing people"
  group: "Things you need to do next"
- id: r19
  title: "See what finance and support is available"
  description: "Look for support, based on where you are, your industry and size."
  url: "/business-finance-support?business_stages%5B%5D=not-yet-trading"
  topic: "Financial help"
  group: "Things you need to do next"
- id: r20
  title: "Get financial support during coronavirus"
  description: "You might be able to get financial support if your business has been affected by coronavirus."
  url: "/business-coronavirus-support-finder"
  topic: "Financial help"
  group: "Things you need to do next"
- id: r21
  title: "Guidance on employing people"
  description: "Read through the rules on employment and looking after your staff."
  url: "/browse/employing-people"
  topic: "Employing people"
  group: "Rules to follow"
- id: r22
  title: "Check the rules on running a business from home"
  description: "You might need extra permissions or insurance when you run your business from home."
  url: "/run-business-from-home"
  topic: "Business location"
  group: "Rules to follow"
- id: r23
  title: "Your responsibilities when renting"
  description: "Follow health and safety rules, and make repairs when required by your lease."
  url: "/renting-business-property-tenant-responsibilities"
  topic: "Business location"
  group: "Rules to follow"
- id: r24
  title: "Find out about rules for business premises"
  description: "Rules that affect your business premises."
  url: "/browse/business/premises-rates"
  topic: "Business location"
  group: "Rules to follow"
- id: r25
  title: "Show a sign where your business operates"
  description: "You need to put up a sign showing your company name at your registered company address and wherever your business operates."
  url: "/running-a-limited-company/signs-stationery-and-promotional-material"
  topic: "Business location"
  group: "Rules to follow"
- id: r26
  title: "How to buy items from abroad"
  description: "Rules you need to follow when importing items into the UK."
  url: "/import-goods-into-uk"
  topic: "Buying and selling"
  group: "Rules to follow"
- id: r27
  title: "How to sell items abroad"
  description: "Rules you need to follow when exporting items out of the UK."
  url: "/export-goods"
  topic: "Buying and selling"
  group: "Rules to follow"
- id: r28
  title: "How and when to charge VAT"
  description: "The rules you need to follow once you're registered for VAT."
  url: "/vat-businesses"
  topic: Tax
  group: "Rules to follow"
- id: r29
  title: "You can register for VAT if you want to"
  description: "You do not have to register for VAT, because your business will take less than £90,000 (the 'turnover')."
  url: "/vat-registration/when-to-register"
  topic: Tax
  group: "Good to know"
- id: r30
  title: "Find out about export markets"
  description: "See where you could be selling your goods or services"
  url: "/research-export-markets"
  topic: "Buying and selling"
  group: "Good to know"
