---
- :name: British dependent territories citizen
  :slug: british-dependent-territories-citizen
- :name: British national overseas
  :slug: british-national-overseas
- :name: British overseas citizen
  :slug: british-overseas-citizen
- :name: British protected person
  :slug: british-protected-person
- :name: Cyprus (northern part of Cyprus)
  :slug: cyprus-north
- :name: Hong Kong (British national overseas)
  :slug: hong-kong-(british-national-overseas)
- :name: Stateless or Refugee
  :slug: stateless-or-refugee
- :name: Vatican City
  :slug: vatican-city
