# Only the current date is used, so this file should only have
# at most 2 items (current and future when uprating is coming),
# and usually 1. The last item in the file should have an end
# date of 2999-01-01
---
- start_date: 2022-04-06
  end_date: 2999-01-01
  maximum_married_couple_allowance: 10375
  minimum_married_couple_allowance: 4010
