# Uses historical data at the moment, so only add items
# to this, do not remove them.
---
- start_date: 2010-04-04
  end_date: 2011-04-02
  lower_earning_limit_rate: 97
- start_date: 2011-04-03
  end_date: 2012-03-31
  lower_earning_limit_rate: 102
- start_date: 2012-04-01
  end_date: 2013-04-06
  lower_earning_limit_rate: 107
- start_date: 2013-04-07
  end_date: 2014-04-05
  lower_earning_limit_rate: 109
- start_date: 2014-04-06
  end_date: 2015-04-04
  lower_earning_limit_rate: 111
- start_date: 2015-04-05
  end_date: 2017-04-01
  lower_earning_limit_rate: 112
- start_date: 2017-04-02
  end_date: 2018-03-31
  lower_earning_limit_rate: 113
- start_date: 2018-04-01
  end_date: 2019-04-06
  lower_earning_limit_rate: 116
- start_date: 2019-04-07
  end_date: 2020-04-04
  lower_earning_limit_rate: 118
- start_date: 2020-04-05
  end_date: 2022-04-05
  lower_earning_limit_rate: 120
- start_date: 2022-04-06
  end_date: 2025-04-05
  lower_earning_limit_rate: 123
- start_date: 2025-04-06
  end_date: 2100-04-03
  lower_earning_limit_rate: 125
