# Only the current date is used, so this file should only have
# at most 2 items (current and future when uprating is coming),
# and usually 1. The last item in the file should have an end
# date of 2999-01-01
---
- start_date: 2024-04-08
  end_date: 2025-04-06
  weekly_rate: 169.50
  lower_weekly_rate: 101.55
- start_date: 2025-04-07
  end_date: 2999-01-01
  weekly_rate: 176.45
  lower_weekly_rate: 105.70
